openapi: 3.1.0
info:
  title: Golden Service API
  version: 0.1.0
servers:
  - url: https://golden-service.example.com
paths:
  /health:
    get:
      summary: Service health
      responses:
        '200':
          description: healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
  /ready:
    get:
      summary: Readiness probe
      responses:
        '200':
          description: ready
  /api/v1/ping:
    get:
      summary: Ping endpoint
      responses:
        '200':
          description: pong
