steps:
  # Extract version from __version__.py
  - name: python:3.12-slim
    entrypoint: python
    args:
      - -c
      - |
        import sys
        sys.path.insert(0, 'api')
        from app import __version__
        with open('/workspace/_version.txt', 'w') as f:
            f.write(__version__)
        print(f"Extracted version: {__version__}")
    id: extract-version
    dir: services/dave

  # Run tests
  - name: python:3.12-slim
    entrypoint: bash
    args:
      - -c
      - |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install ruff==0.0.284 pyright==1.1.378 pytest schemathesis hypothesis bandit semgrep
        ruff check api tests
        pyright
        pytest
    dir: services/dave

  # Build Docker image with version tags
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        VERSION=$(cat /workspace/_version.txt)
        docker build \
          -t gcr.io/$PROJECT_ID/dave-service:$SHORT_SHA \
          -t gcr.io/$PROJECT_ID/dave-service:$VERSION \
          -t gcr.io/$PROJECT_ID/dave-service:latest \
          -f services/dave/Dockerfile \
          --build-arg VERSION=$VERSION \
          .
    id: build-image

  # Push all tags
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        VERSION=$(cat /workspace/_version.txt)
        docker push gcr.io/$PROJECT_ID/dave-service:$SHORT_SHA
        docker push gcr.io/$PROJECT_ID/dave-service:$VERSION
        docker push gcr.io/$PROJECT_ID/dave-service:latest
        echo "Pushed images with tags: $SHORT_SHA, $VERSION, latest"

images:
  - gcr.io/$PROJECT_ID/dave-service:$SHORT_SHA
  - gcr.io/$PROJECT_ID/dave-service:latest

# Note: Version-tagged image (gcr.io/$PROJECT_ID/dave-service:$VERSION) is also pushed
# but not listed here to avoid Cloud Build trying to re-push it
