name: Task
description: Create a task for technical work, improvements, or chores
title: "[TASK] "
labels: ["type-task", "status-needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for creating a task! Use this template for technical work, refactoring, documentation, or general improvements.

  - type: textarea
    id: task-description
    attributes:
      label: Task Description
      description: A clear and concise description of the work to be done.
      placeholder: Describe what needs to be accomplished...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context & Motivation
      description: Why is this task important? What problem does it solve?
      placeholder: Explain the background and reasoning...
    validations:
      required: true

  - type: dropdown
    id: task-type
    attributes:
      label: Task Type
      description: What kind of work is this?
      options:
        - Refactoring
        - Technical Debt
        - Infrastructure
        - Documentation
        - Testing
        - Configuration
        - Dependencies
        - Performance
        - Security Hardening
        - Code Cleanup
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How urgent is this task?
      options:
        - Low (nice to have, not urgent)
        - Medium (should be done soon)
        - High (important for stability/quality)
        - Critical (blocking other work)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component/Area
      description: What part of the system does this affect?
      options:
        - Frontend/UI
        - Backend/API
        - Database
        - Authentication
        - Infrastructure
        - CI/CD
        - Documentation
        - Testing
        - Configuration
        - Multiple Areas
        - Other
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How will we know this task is complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
      value: |
        - [ ]
    validations:
      required: true

  - type: textarea
    id: implementation-notes
    attributes:
      label: Implementation Notes
      description: Any technical details, approaches, or constraints to consider?
      placeholder: |
        - Specific files to modify
        - Technical approach
        - Dependencies or prerequisites
        - Testing strategy

  - type: textarea
    id: related-issues
    attributes:
      label: Related Issues/PRs
      description: Link to related issues, PRs, or documentation
      placeholder: |
        - Fixes #123
        - Related to #456
        - Blocked by #789

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex is this task?
      options:
        - Simple (< 2 hours)
        - Medium (2-8 hours)
        - Complex (1-3 days)
        - Major (> 3 days)
        - Unknown
    validations:
      required: true

  - type: checkboxes
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Will this task introduce any breaking changes?
      options:
        - label: This task includes breaking changes that require migration
        - label: This task affects public APIs or interfaces
        - label: This task requires database migrations
        - label: This task requires environment variable changes
        - label: No breaking changes expected

  - type: checkboxes
    id: testing-requirements
    attributes:
      label: Testing Requirements
      description: What testing is needed for this task?
      options:
        - label: Unit tests required
        - label: Integration tests required
        - label: Manual testing required
        - label: Performance testing required
        - label: Security testing required
        - label: Documentation update required

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, research, or examples here.
      placeholder: Any additional information that might help...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this task hasn't been created already
          required: true
        - label: I have provided sufficient detail to understand the scope of work
          required: true
